### ISSUE TITLE
 Linux Flatpak: Manual plugin install #66 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#10]
https://github.com/OpenCPN/OpenCPN/issues/2178#issuecomment-832054747

**Comment by leamas** [comment]
Manual plugin install is, flatpak or not, about making a local build and import the plugin.  How a localbuild is done is a question for the plugin (practically, in most cases the testplugin or shipdriver templates).

The issue linked above was basically about a user having problems making a local build. As I see it, this is not really an general plugin development issue. So: what is the issue here, really?

**Comment by rgleason** [comment]
So where in shipdriver template documentation do you show how to build locally and install?

**Comment by leamas** [comment]
All shipdriver plugins comes with a INSTALL.md, which is sort of an established name for this. See for example https://github.com/Rasbats/shipdriver_pi/blob/master/INSTALL.md. Currently, this points to the wiki but will be updated to point to the development manual instead.

**Comment by rgleason** [comment]
Yes, I guess the link should be added to shipdriver template.
We will try to follow that outline when we start working on testpllugin template.
