### ISSUE TITLE
 plugins Alpha channel and use of Meta-urls for testing Android and Ubuntu etc. #71 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#15]
https://github.com/OpenCPN/plugins/issues/381
Also add how to turn on this feature by using the expert key

[PlugIns]
catalogexpert=1

**Comment by rgleason** [comment]
This is a good tool for Plugin Devs to use for testing their plugins on various platforms because

    Setting up your own meta-url allows /plugins/metadata Alpha branch updates to show in the PIM without having to make a PR to opencpn/plugins Alpha branch and having bdbcat accept it.
    Tarballs do not need to be copied to multiple OS for testing.
    PIM system can be used on the Alpha catalog

This is a Plugin Developer technique that should be used more.

**Comment by leamas** [comment]
There is a beginning in modules/ROOT/pages/pi_installer_catalog_meta.adoc. One problem here is that it contains both how to make a pull request and how to setup the meta-url. The pull request stuff must be moved out of here since it's specific for testplugin. Shipdriver has a totally different way of creating a PR.

**Comment by rgleason** [comment]
I've moved this under Testplugin and will deal with it when we Author Testplugin..  Closing.

**Comment by leamas** [comment]
Isn't  this a pity? The core procedure how to create a meta-url should be the same for both templates, right?

**Comment by rgleason** [comment]
No it is unique to testplugin. SD has a completely different process

**Comment by leamas** [comment]
OK.
