### ISSUE TITLE
 Set a pre-commit hook for all plugins to verify urls #80 

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/development#16]
https://github.com/rgleason/weather_routing_pi/issues/76#issuecomment-893485623

**Comment by leamas** [comment]
Sorry, this doesn't really  make sense here. The pre-commit hooks are specialized creatures, and what's possible in the plugins project is not necessarily applicable here.

We *could* make  pre-commit  hook which verifies all urls in the committed data using linkchecker. However, this is not easy to install on all platforms. Also, we have a different need of being able to make quick fixes here that doesn't blend well with a heavy pre-commit hook.

I think we should close this bug, as for the pre-commit stuff. What we could do is adding instructoins to WORKFLOWS how to do local tests on the generated site before committing. But that's something else, for sure.

**Comment by rgleason** [comment]
Maybe I mis-understood something here.  
Plugin Authors do not need to set a pre-commit hook?
Fine.
Then who does need to set one?  And why did I need to set one?

**Comment by leamas** [comment]
We need to set one, but not that one. What *we* need is a check to avoid white-space problems. This is a simple and fast hook that works also for us. But while checking urls is fine in the plugins project, i just don't think it fits really well here.

Here, the reason is that unless we use the hook there will be white-space problems. Besides just being frowned upon, such problems makes patches and rebasing needlessly hard.

I have added a section in WORKFLOWS in 3f4a3319. Could we close this bug with this?
